name: TEST_BUILD_ANGULAR_NODE
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BUILD_AL:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: build-app
        run: |
          git clone https://github.com/vmware/data-annotator-for-machine-learning.git master
          cd master/annotation-app
          npm i
      
      - name: run-app
        run: |
          cd master/annotation-app
          npm start &
          sleep 15
          
      - name: build-service
        run: |
          cd master/annotation-service
          npm i

      - name: run-service
        run: |
          cd master/annotation-service
          npm start &
          sleep 15

      - name: connect-application
        run: |
          sleep 10
          echo ----------------------CONNECT TO THE APP------------------------------------
          curl http://localhost:4200
          echo ----------------------CONNECT TO THE SERVICE------------------------------------
          curl http://localhost:3000/health
