name: TEST_BUILD_AL
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BUILD_AL:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node ${{ matrix.python-version }}
        uses: actions/setup-node@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: build-app
        run: |
          git clone https://github.com/vmware/data-annotator-for-machine-learning.git master
          cd master/annotation-app
          npm i
      
      - name: run-al
        run: |
          cd master/annotation-app
          npm start
