name: TEST_BUILD_AL
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BUILD_AL:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: [ '3.7', '3.8', '3.9' ] # 3.6 not found, '3.10' not support
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: set-up-mongodb
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '4.4'
      - name: show-current-python-version
        run: |
          python --version
          pip --version
      
      - name: set-up-python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: build-al
        run: |
          git clone https://github.com/vmware/data-annotator-for-machine-learning.git master
          cd master/active-learning-service
          pip install -r requirements.txt
      
      - name: run-al
        run: |
          cd master/active-learning-service
          python manage.py runserver localhost:8000 &
          sleep 120
      
      - name: BUILD-END-CHECK-PYTHON-VERSION
        run: |
          python --version
          pip --version
