name: TEST_RUN_WITH_DOCKER
on:
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BUILD_AL:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: run-app
        run: |
            docker run --name app 1107899648/vmware-daml-annotation-app:latest
